### ISSUE TITLE
Trouble following Quickstart

### ISSUE THREAD

**Issue by mdeimel** [basilisk-fw/basilisk#1]
I had the following issues when testing out the Quickstart guide.

First I had a `checkstyle` error:

```
<file name="/.../sample/src/main/java/org/example/ApplicationEventHandler.java">
   <error line="3" column="8" severity="error" message="Unused import - basilisk.core.BasiliskApplication." source="com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck"/>
</file>
```

So I commented out the unused import in `BasiliskApplication`.

Then I received the following error:

```
Execution failed for task ':test'.
> When running gradle with java 8, you must set the path to the old jdk, either with property retrolambda.oldJdk or environment variable JAVA6_HOME/JAVA7_HOME
```

I tried setting `JAVA7_HOME` to the home directory of jdk7 on my Mac, but the same error still occurs.

**Comment by aalmiray** [comment]
Updated the template to remove unused imports. I can't get the project to fail with Java8 as you mentioned. Could you give us a little more of detail on your setup? I have the following

    ------------------------------------------------------------
    Gradle 2.7
    ------------------------------------------------------------

    Build time:   2015-09-14 07:26:16 UTC
    Build number: none
    Revision:     c41505168da69fb0650f4e31c9e01b50ffc97893

    Groovy:       2.3.10
    Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
    JVM:          1.8.0_51 (Oracle Corporation 25.51-b03)
    OS:           Mac OS X 10.10.5 x86_64

**Comment by mdeimel** [comment]
Initially I had the following information:

```
------------------------------------------------------------
Gradle 2.2.1
------------------------------------------------------------

Build time:   2014-11-24 09:45:35 UTC
Build number: none
Revision:     6fcb59c06f43a4e6b1bcb401f7686a8601a1fb4a

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
OS:           Mac OS X 10.10.5 x86_64
```

So I tried switching to the following

```
------------------------------------------------------------
Gradle 2.7
------------------------------------------------------------

Build time:   2015-09-14 07:26:16 UTC
Build number: none
Revision:     c41505168da69fb0650f4e31c9e01b50ffc97893

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
OS:           Mac OS X 10.10.5 x86_64
```

And I still receive the same error.

Also, I have the `JAVA7_HOME` environment variable set to: `/Library/Java/JavaVirtualMachines/jdk1.7.0_15.jdk/Contents/Home`

**Comment by kimukou** [comment]
i have same error.
i can run edit build.gradle after create project

- build.gradle
```build.gradle
retrolambda {
    jdk '/usr/libexec/java_home -v 1.8'.execute().text
    oldJdk '/usr/libexec/java_home -v 1.7'.execute().text
}
```

**Comment by aalmiray** [comment]
you can also append the following to `build.gradle`

    retrolambda {
        javaVersion JavaVersion.VERSION_1_7
    }

however some Basilisk internals were released with JDK8 compatibility and will still make test fail. Wew expect to fix this problem in the next release

**Comment by aalmiray** [comment]
Retrolambda is no longer used by the latest versions of the `jfxmobile` plugin.
